import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Divider, Row, Col, Button } from "antd";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3>Home Page</h3>
        <Divider />
        <Row gutter={20}>
          <Col span={6}>
            <Button type="primary" onClick={() => router.push('/services')}>Go to Services page</Button>
          </Col>
          <Col span={6}>
            <Button onClick={() => router.push('/about-us')}>Go to About us page</Button>
          </Col>
        </Row>
      </main>
    </>
  );
}
